const WEIGHT_SPAM = 'weightSpam'
const WEIGHT_BAD_WORDS = 'weightBadWords'
const WEIGHT_MISSPELLING = 'weightMisspelling'
const WEIGHT_TEXT = 'weightText'
const WEIGHT_USER = 'weightUser'
const WEIGHT_SOCIAL = 'weightSocial'